<?xml version="1.0"?>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at https://mozilla.org/MPL/2.0/. -->
<!-- TODO merge unitree_go1.urdf.xacro -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="unitree_go1">
  <xacro:arg name="use_gazebo" default="true"/>
  <xacro:arg name="use_ros2_control" default="true"/>
  <xacro:arg name="use_gz" default="true"/>
  <xacro:arg name="ign_compatible" default="false"/>
  <!-- Enable depth camera simulation for ignition gazebo -->
  <xacro:arg name="enable_sensors_plugin" default="false"/>
  <xacro:arg name="enable_low_resolution_depth" default="true"/>
  <xacro:arg name="enable_unitree_depth_camera" default="true"/>
  <xacro:arg name="enable_backpack_mesh" default="false"/>
  <xacro:include filename="$(find unitree_go1_description)/urdf/const.xacro"/>
  <xacro:include filename="$(find unitree_go1_description)/urdf/materials.xacro"/>
  <xacro:if value="$(arg use_gazebo)">
    <xacro:include filename="$(find unitree_go1_description)/urdf/gazebo.xacro"/>
  </xacro:if>
  <xacro:include filename="$(find unitree_go1_description)/urdf/leg.xacro"/>
  <xacro:include filename="$(find unitree_go1_description)/urdf/depthCamera.xacro"/>
  <xacro:include filename="$(find unitree_go1_description)/urdf/ultraSound.xacro"/>
  <xacro:include filename="$(find unitree_go1_description)/urdf/ros2_control.xacro"/>
  <xacro:include filename="$(find unitree_go1_description)/urdf/backpack_sensor_unit.xacro"/>
  <!-- Rollover Protection mode will add an additional stick on the top, use "true" or "false" to switch it. -->
  <xacro:property name="rolloverProtection" value="false"/>
  <!-- Debug mode will hung up the robot, use "true" or "false" to switch it. -->
  <xacro:arg name="DEBUG" default="false"/>
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </visual>
  </link>
  <joint name="floating_base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="trunk"/>
  </joint>
  <link name="trunk">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://unitree_go1_description/meshes/visual/trunk.dae" scale="1 1 1"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${trunk_length} ${trunk_width} ${trunk_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
      <mass value="${trunk_mass}"/>
      <inertia ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}" iyy="${trunk_iyy}" iyz="${trunk_iyz}" izz="${trunk_izz}"/>
    </inertial>
  </link>
  <xacro:if value="${(rolloverProtection == 'true')}">
    <joint name="stick_joint" type="fixed">
      <parent link="trunk"/>
      <child link="stick_link"/>
      <origin rpy="0 0 0" xyz="${0.18} 0 ${stick_length/2.0+0.08}"/>
    </joint>
    <link name="stick_link">
      <visual>
        <geometry>
          <cylinder length="${stick_length}" radius="${stick_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="silver"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${stick_length}" radius="${stick_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${stick_mass}"/>
        <inertia ixx="${stick_mass / 2.0 * (stick_radius*stick_radius)}" ixy="0.0" ixz="0.0" iyy="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}" iyz="0.0" izz="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}"/>
      </inertial>
    </link>
  </xacro:if>
  <joint name="imu_joint" type="fixed">
    <parent link="trunk"/>
    <child link="imu_link"/>
    <origin rpy="0 0 0" xyz="-0.01592 -0.06659 -0.00617"/>
  </joint>
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>
  <xacro:leg name="fr" mirror="-1" mirror_dae="False" front_hind="1" front_hind_dae="True">
    <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} 0"/>
  </xacro:leg>
  <xacro:leg name="fl" mirror="1" mirror_dae="True" front_hind="1" front_hind_dae="True">
    <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} 0"/>
  </xacro:leg>
  <xacro:leg name="rr" mirror="-1" mirror_dae="False" front_hind="-1" front_hind_dae="False">
    <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} 0"/>
  </xacro:leg>
  <xacro:leg name="rl" mirror="1" mirror_dae="True" front_hind="-1" front_hind_dae="False">
    <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} 0"/>
  </xacro:leg>
  <xacro:depthCamera camID="1" name="face">
    <origin rpy="${PI} 0 0" xyz="0.2785 0.0125 0.0167"/>
  </xacro:depthCamera>
  <xacro:depthCamera camID="2" name="chin">
    <origin rpy="${PI} ${PI/2} 0" xyz="0.2522 0.0125 -0.0436"/>
  </xacro:depthCamera>
  <xacro:depthCamera camID="3" name="left">
    <origin rpy="${PI} 0.2618 ${PI/2}" xyz="-0.066 0.082 -0.0176"/>
  </xacro:depthCamera>
  <xacro:depthCamera camID="4" name="right">
    <origin rpy="${PI} 0.2618 ${-PI/2}" xyz="-0.041 -0.082 -0.0176"/>
  </xacro:depthCamera>
  <xacro:depthCamera camID="5" name="rearDown">
    <origin rpy="${PI} ${PI/2} 0" xyz="-0.0825 0.0125 -0.04365"/>
  </xacro:depthCamera>
  <joint name="camera_laserscan_left_joint" type="fixed">
    <origin rpy="0 0.2618 0" xyz="0 0 0"/>
    <parent link="camera_left"/>
    <child link="camera_laserscan_left_link"/>
  </joint>
  <link name="camera_laserscan_left_link">
    </link>
  <joint name="camera_laserscan_right_joint" type="fixed">
    <origin rpy="0 0.2618 0" xyz="0 0 0"/>
    <parent link="camera_right"/>
    <child link="camera_laserscan_right_link"/>
  </joint>
  <link name="camera_laserscan_right_link">
    </link>
  <xacro:ultraSound name="left">
    <origin rpy="0 0.2618 ${PI/2}" xyz="-0.0535  0.0826 0.00868"/>
  </xacro:ultraSound>
  <xacro:ultraSound name="right">
    <origin rpy="0 0.2618 ${-PI/2}" xyz="-0.0535 -0.0826 0.00868"/>
  </xacro:ultraSound>
  <xacro:ultraSound name="face">
    <origin rpy="0 0 0" xyz="0.2747 0.0 -0.0088"/>
  </xacro:ultraSound>
  <xacro:backpack_sensor_unit name="tc23" parent="base_link">
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </xacro:backpack_sensor_unit>
</robot>
