controller_manager:
  ros__parameters:
    update_rate: 500
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    open_loop_control: false
    state_publish_rate: 450.0
    acrion_monitor_rate: 450.0
    allow_partial_joint_goal: false
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - fr_hip_joint
      - fr_thigh_joint
      - fr_calf_joint
      - fl_hip_joint
      - fl_thigh_joint
      - fl_calf_joint
      - rr_hip_joint
      - rr_thigh_joint
      - rr_calf_joint
      - rl_hip_joint
      - rl_thigh_joint
      - rl_calf_joint
